package:
  name:torchquant
  version:1.0.1

source:
  path: .

build:
  number:0
  script:python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

test:
  imports:
    - torchquant

about:
  home:
  license: Apache License 2.0